-- AlterTable
ALTER TABLE "Invoice" 
  ADD COLUMN "totalWeightKg" DOUBLE PRECISION DEFAULT 0,
  ADD COLUMN "protectorsAmount" DOUBLE PRECISION DEFAULT 0,
  ADD COLUMN "totalAmount" DOUBLE PRECISION DEFAULT 0;

